Create Fjord: Failure Modes and Recovery Path Analysis (Draft)
ethereum-optimism/design-docs pull request #23
Opened 2024-05-23 13:39 UTC by BlocksOnAChain

This commits adds the initial draft version of the FMA for the Fjord hardfork.

**Description**
We want to publish our  initial draft version for the Fjord FMA and share it as out with other dev teams.

A clear and concise description of the features you're adding in this pull request.
Fjord FMA draft will be published when we merge this PR.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.
_No tests needed_

2024-05-23 13:59 UTC, sebastianst commented on security/Fjord: Failure Modes and Recovery Path Analysis
better make this file a markdown file like `fjord-fma.md` and then put the title at the top

2024-05-23 16:12 UTC, BlocksOnAChain commented on security/Fjord: Failure Modes and Recovery Path Analysis
@sebastianst I did address it in my recent PR change, feel free to review and merge if you are happy with it.

2024-05-24 12:48 UTC, BlocksOnAChain commented on security/Fjord: Failure Modes and Recovery Path Analysis
@sebastianst done from my side, feel free to review it.

2024-05-30 08:22 UTC, sebastianst commented on security/Fjord: Failure Modes and Recovery Path Analysis
I'd prefer to keep with the convention in this repo and name the file exactly `fjord-fma.md` with small `f`, not capital `F`.

2024-05-30 08:26 UTC, sebastianst requested changes
We also need to add sections regarding FP upgrade failure modes

2024-05-30 08:26 UTC, sebastianst commented on security/Fjord-fma.md
> +- Protocol quest [issues](https://github.com/ethereum-optimism/protocol-quest/issues?q=is%3Aissue+Fjord+) related to Fjord.
```suggestion
```
it's internal, better remove

2024-05-30 08:26 UTC, sebastianst commented on security/Fjord-fma.md
> +- **Recovery Path(s)**: *How do we resolve this? Is it a simple, quick recovery or a big effort? Would recovery require a governance vote or a hard fork?*
still need to fill this out, can do in a follow up I guess?

2024-05-30 09:52 UTC, BlocksOnAChain commented on security/Fjord-fma.md
> +- **Recovery Path(s)**: *How do we resolve this? Is it a simple, quick recovery or a big effort? Would recovery require a governance vote or a hard fork?*
yeah, I think we can do it later

2024-05-30 09:54 UTC, BlocksOnAChain commented on security/Fjord: Failure Modes and Recovery Path Analysis
ok done from my side.

2024-05-30 12:57 UTC, BlocksOnAChain reviewed
sounds good to me @mds1

2024-06-04 08:52 UTC, BlocksOnAChain commented on security/fjord-fma.md
@sebastianst are we ok to merge it now?

2024-06-10 11:37 UTC, sebastianst commented on security/fjord-fma.md
@mds1 asks to rename it to `fma-fjord`, it's currently called `fjord-fma`.

2024-06-10 15:18 UTC, BlocksOnAChain reviewed
made small edits + changed the name to match the format we are using.

2024-06-10 15:20 UTC, BlocksOnAChain commented on security/fjord-fma.md
@sebastianst @mds1   - the file is now called "fma-fjord", I added the most recent edits we had in the notion doc so we have a matching public version.
I think it would be good to go now, after your reviews.

2024-06-12 17:37 UTC, sebastianst approved these changes

2024-06-12 19:19 UTC, mds1 approved these changes

2024-06-12 19:19 UTC, merged